version: '3.7'

services:
  # App services
  lycoris-app-1:
    image: tigolifrederic283/lycoris-app:1.0
    environment:
      - APP_INSTANCE=1
    container_name: lycoris-app-1
    networks:
      - lycoris-network
    volumes:
      - ./lycoris-app/httpd.conf:/etc/httpd/httpd.conf
      - ./lycoris-app/lycoris.conf:/etc/httpd/conf.d/lycoris.conf
    expose:
      - 80
  lycoris-app-2:
    image: tigolifrederic283/lycoris-app:1.0
    environment:
      - APP_INSTANCE=2
    container_name: lycoris-app-2
    networks:
      - lycoris-network
    volumes:
      - ./lycoris-app/httpd.conf:/etc/httpd/httpd.conf
      - ./lycoris-app/lycoris.conf:/etc/httpd/conf.d/lycoris.conf
    expose: 
      - 80
  # Api services
  lycoris-api-1:
    image: tigolifrederic283/lycoris-api:1.0
    environment:
      - APP_INSTANCE=1
    container_name: lycoris-api-1
    networks:
      - lycoris-network

  lycoris-api-2:
    image: tigolifrederic283/lycoris-api:1.0
    environment:
      - APP_INSTANCE=2
    container_name: lycoris-api-2
    networks:
      - lycoris-network

  # db-galera services
  db-node1:
    image: mariadb:10.6
    expose: 
      - "4567"
      - "4568"
      - "4444"
    depends_on: 
      - db-node2
      - db-node3
    container_name: lycoris-db-node1
    environment:
      - MARIADB_ROOT_PASSWORD=P@ssword2024
    volumes:
      - ./db/galera1.cnf:/etc/mysql/conf.d/galera.cnf
      - ./db/db_lycoris.sql:/docker-entrypoint-initdb.d/db_lycoris.sql
    networks:
      - lycoris-network
    command: ["mysqld", "--wsrep-new-cluster"]
 
  db-node2:
    image: mariadb:10.6
    expose:
      - "4567"
      - "4568"
      - "4444"
    container_name: lycoris-db-node2
    environment:
      - MARIADB_ROOT_PASSWORD=P@ssword2024
    volumes:
      - ./db/galera2.cnf:/etc/mysql/conf.d/galera.cnf
      - ./db/db_lycoris.sql:/docker-entrypoint-initdb.d/db_lycoris.sql
    networks:
      - lycoris-network

  db-node3:
    image: mariadb:10.6
    expose:
      - "4567"
      - "4568"
      - "4444"
    container_name: lycoris-db-node3
    environment:
      - MARIADB_ROOT_PASSWORD=P@ssword2024
    volumes:
      - ./db/galera3.cnf:/etc/mysql/conf.d/galera.cnf
      - ./db/db_lycoris.sql:/docker-entrypoint-initdb.d/db_lycoris.sql
    networks:
      - lycoris-network

  # haproxy service
  haproxy-front:
    image: haproxy:3.1-dev4
    depends_on:
      - lycoris-app-1
      - lycoris-app-2
    container_name: lycoris-ha-1
    volumes:
      - ./ha-proxy/haFront.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - lycoris-network
    ports:
      - 8000:8000

  haproxy-back:
    image: haproxy:3.1-dev4
    container_name: lycoris-ha-2
    depends_on:
      - lycoris-api-1
      - lycoris-api-2
      - db-node1
    volumes:
      - ./ha-proxy/haBack.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - lycoris-network
    ports:
      - 8001:8001
  #redis lycoris
  redis:
    image: redis:7.4.0
    container_name: lycoris-redis
    volumes: 
      - ./lycoris-api/redis.conf:/usr/local/etc/redis/redis.conf
    networks: 
      - lycoris-network

networks:
  lycoris-network:
    driver: bridge

