import { RouteInfo } from "./sidebar.metadata";

export const ROUTES: RouteInfo[] = [
  // {
  //   path: "",
  //   title: "Menu principal",
  //   moduleName: "",
  //   iconType: "",
  //   icon: "",
  //   class: "",
  //   groupTitle: true,
  //   badgeClass: "",
  //   role: ["All"],
  //   submenu: [],
  // },

  // Admin Modules

  {
    path: "/admin/dashboard/main",
    title: "Tableau de bord",
    moduleName: "dashboard",
    iconType: "home",
    icon: "home",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    code: "FUNC-6RWG",
    submenu: [],
  },
  {
    path: "/num-sensible",
    title: "Liste des Numéros",
    moduleName: "num-sensible",
    //iconType: "clock",
    iconType: "phone",
    icon: "dryer",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    code: "FUNC-LA3R",
    submenu: [],
  },
  {
    path: "",
    title: "Actions Unitaires",
    moduleName: "actions-uniques",
    iconType: "cogs",
    icon: "dryer",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    code: "FUNC-LA3R",
    submenu: [
      {
        path: "/actions-uniques/blocage",
        title: "Blocage unitaire",
        moduleName: "blocage",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        code: "FUNC-LA3R",
        submenu: []
      },
      {
        path: "/actions-uniques/deblocage",
        title: "Deblocage unitaire",
        moduleName: "deblocage",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        code: "FUNC-3HZ8",
        submenu: []
      },
      {
        path: "/actions-uniques/mise-en-machine",
        title: "mise en machine unitaire",
        moduleName: "mise-en-machine",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        code: "FUNC-NZTE",
        submenu: []
      },
      {
        path: "/actions-uniques/transfert-corbeille",
        title: "Transfert Corbeille Unique",
        moduleName: "transfert-corbeille",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        code: "FUNC-AY0K",
        submenu: []
      }
    ]
  },
  {
    path: "",
    title: "Liste des demandes",
    moduleName: "liste-demandes",
    iconType: "book",
    icon: "dryer",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    code: "FUNC-YQCJ",
    submenu: [
      {
        path: "/liste-demandes/demandes-en-attente",
        title: "Demandes en attente",
        moduleName: "all-demandes",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        code: "FUNC-YQCJ",
        submenu: []
      },
      {
        path: "/liste-demandes/demandes-acceptées",
        title: "Demande acceptées",
        moduleName: "demande-acceptee",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        code: "FUNC-YQCJ",
        submenu: []
      },
      {
        path: "/liste-demandes/demandes-refusées",
        title: "Demandes refusées",
        moduleName: "demande-refusee",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        code: "FUNC-YQCJ",
        submenu: []
      }
    ]
  },
  /*{
    path: "/demande",
    title: "Liste des demandes",
    moduleName: "demande",
    iconType: "book",
    icon: "dryer",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    code: "FUNC-YQCJ",
    submenu: [],
  },*/


  // {
  //   path: "",
  //   title: "Gestion administrative",
  //   moduleName: "gestion-administrative",
  //   iconType: "clock",
  //   icon: "plus",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   code: "86372296",
  //   submenu: [
  //     {
  //       path: "/gestion-administrative/gestion-vacations",
  //       title: "Gestion des vacations",
  //       moduleName: "gestion-vacations",
  //       iconType: "list",
  //       icon: "plus",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "57344196",
  //       submenu: [
  //         {
  //           path: "/gestion-administrative/gestion-vacations/vacataire",
  //           title: "Vacataires",
  //           moduleName: "gestion-vacations",
  //           iconType: "list",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "82209945",
  //           submenu: [],
  //         },
  //         {
  //           path: "/gestion-administrative/gestion-vacations/vacations",
  //           title: "Vacation",
  //           moduleName: "gestion-vacations",
  //           iconType: "list",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "82209945",
  //           submenu: [],
  //         },
  //         {
  //           path: "/gestion-administrative/gestion-vacations/traitements",
  //           title: "Traitement honoraires",
  //           moduleName: "gestion-vacations",
  //           iconType: "list",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "82209945",
  //           submenu: [],
  //         },
  //         {
  //           path: "/gestion-administrative/gestion-vacations/validation",
  //           title: "Validation honoraires",
  //           moduleName: "gestion-vacations",
  //           iconType: "list",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "82209945",
  //           submenu: [],
  //         },
  //         {
  //           path: "/gestion-administrative/gestion-vacations/reglement",
  //           title: "Règlement honoraires",
  //           moduleName: "gestion-vacations",
  //           iconType: "list",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "82209945",
  //           submenu: [],
  //         },
  //       ],
  //     },
  //     {
  //       path: "/gestion-administrative/rdv",
  //       title: "Prise de rendez-vous",
  //       moduleName: "gestion-administrative",
  //       iconType: "list",
  //       icon: "plus",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "57344196",
  //       submenu: [

  //       ],
  //     },
  //     {
  //       path: "/gestion-administrative/planning",
  //       title: "Planning",
  //       moduleName: "planning",
  //       iconType: "calendar",
  //       icon: "plus",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "82209945",
  //       submenu: [
  //         {
  //           path: "/gestion-administrative/planning/planning",
  //           title: "Création de planning",
  //           moduleName: "planning",
  //           iconType: "list",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "82209945",
  //           submenu: [],
  //         },
  //         {
  //         path: "/gestion-administrative/planning/gestion",
  //         title: "Disponibilité",
  //         moduleName: "planning",
  //         iconType: "list",
  //         icon: "",
  //         class: "ml-menu",
  //         groupTitle: false,
  //         badge: "",
  //         badgeClass: "",
  //         code: "82209945",
  //         submenu: [],
  //       },
  //       {
  //         path: "/gestion-administrative/planning/consulter-planning",
  //         title: "Consultation planning",
  //         moduleName: "planning",
  //         iconType: "list",
  //         icon: "",
  //         class: "ml-menu",
  //         groupTitle: false,
  //         badge: "",
  //         badgeClass: "",
  //         code: "82209945",
  //         submenu: [],
  //       },
  //       {
  //         path: "/gestion-administrative/planning/edition-programme",
  //         title: "Edition de programme",
  //         moduleName: "planning",
  //         iconType: "list",
  //         icon: "",
  //         class: "ml-menu",
  //         groupTitle: false,
  //         badge: "",
  //         badgeClass: "",
  //         code: "82209945",
  //         submenu: [],
  //       }
  //     ],
  //     },
  //     {
  //       path: "",
  //       title: "Reclamation",
  //       moduleName: "reclamation",
  //       iconType: "clock",
  //       icon: "plus",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "86372296",
  //       submenu: [
  //         {
  //           path: "/gestion-administrative/reclamation/register",
  //           title: "Enregistrement de plainte",
  //           moduleName: "reclamation",
  //           iconType: "list",
  //           icon: "plus",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "57344196",
  //           submenu: [],
  //         },
  //         {
  //           path: "/gestion-administrative/reclamation/imputation-plainte",
  //           title: "Imputation plainte",
  //           moduleName: "reclamation",
  //           iconType: "list",
  //           icon: "plus",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "57344196",
  //           submenu: [],
  //         },

  //         {
  //           path: "/gestion-administrative/reclamation/justificatif-medecin",
  //           title: "Justification medecin",
  //           moduleName: "reclamation",
  //           iconType: "list",
  //           icon: "plus",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "57344196",
  //           submenu: [],
  //         },
  //         {
  //           path: "/gestion-administrative/reclamation/analyse",
  //           title: "Analyse et traitement",
  //           moduleName: "reclamation",
  //           iconType: "clock",
  //           icon: "plus",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "47739289",
  //           submenu: [],
  //         },
  //         {
  //           path: "/gestion-administrative/reclamation/reglement-plainte",
  //           title: "Règlement de la plainte",
  //           moduleName: "reclamation",
  //           iconType: "clock",
  //           icon: "plus",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "47739289",
  //           submenu: [],
  //         },
  //         {
  //           path: "/gestion-administrative/reclamation/process",
  //           title: "Vérification et décisions",
  //           moduleName: "reclamation",
  //           iconType: "clock",
  //           icon: "plus",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "99244392",
  //           submenu: [],
  //         },
  //       ],
  //     },
  //   ],
  // },


  // {
  //   path: "",
  //   title: "Bureau des entrées",
  //   moduleName: "bureau-des-entrees",
  //   iconType: "users",
  //   icon: "plus",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   code: "50194393",
  //   submenu: [
  //     {
  //       path: "/bureau-des-entrees/accueil-reception",
  //       title: "Accueil / Reception",
  //       moduleName: "accueil-reception",
  //       iconType: "list",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "32663120",
  //       submenu: [
  //           {
  //               path: "/bureau-des-entrees/accueil-reception/acceuil",
  //               title: "Accueil",
  //               moduleName: "accueil-reception",
  //               iconType: "list",
  //               icon: "plus",
  //               class: "ml-menu",
  //               groupTitle: false,
  //               badge: "",
  //               badgeClass: "",
  //               code: "61279014",
  //               submenu: [],
  //           },

  //           {
  //             path: "/bureau-des-entrees/accueil-reception/client",
  //             title: "Clients",
  //             moduleName: "accueil-reception",
  //             iconType: "list",
  //             icon: "plus",
  //             class: "ml-menu",
  //             groupTitle: false,
  //             badge: "",
  //             badgeClass: "",
  //             code: "61279014",
  //             submenu: [],
  //         }
  //       ],
  //     },
  //     {
  //       path: "/bureau-des-entrees/remboursement",
  //       title: "Remboursements",
  //       moduleName: "remboursement",
  //       iconType: "money",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "18421593",
  //       submenu: [
  //         {
  //           path: "/bureau-des-entrees/remboursement/actes-externes",
  //           title: "Actes externes",
  //           moduleName: "remboursement",
  //           iconType: "list",
  //           icon: "plus",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "61279014",
  //           submenu: [],
  //       },
  //       {
  //         path: "/bureau-des-entrees/remboursement/pharmacie-vente-prescription",
  //         title: "Ordonnance interne",
  //         moduleName: "remboursement",
  //         iconType: "list",
  //         icon: "plus",
  //         class: "ml-menu",
  //         groupTitle: false,
  //         badge: "",
  //         badgeClass: "",
  //         code: "61279014",
  //         submenu: [],
  //     },
  //     {
  //       path: "/bureau-des-entrees/remboursement/pharmacie-vente-direct",
  //       title: "Ordonnance externes",
  //       moduleName: "remboursement",
  //       iconType: "list",
  //       icon: "plus",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "61279014",
  //       submenu: [],
  //   },
  //   {
  //     path: "/bureau-des-entrees/remboursement/validation",
  //     title: "Validation",
  //     moduleName: "remboursement",
  //     iconType: "list",
  //     icon: "plus",
  //     class: "ml-menu",
  //     groupTitle: false,
  //     badge: "",
  //     badgeClass: "",
  //     code: "61279014",
  //     submenu: [],
  // }
  //       ],
  //     },
  //   ],
  // },

  // {
  //   path: "/tresorerie/main-tresorerie",
  //   title: "Trésorerie",
  //   moduleName: "tresorerie",
  //   iconType: "money-bill",
  //   icon: "monetization_on",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   code: "90114807",
  //   submenu: [
  //     {
  //       path: "/tresorerie/main-tresorerie/mouvement-caisse",
  //       title: "Mouvement caisse",
  //       moduleName: "main-tresorerie",
  //       iconType: "list",
  //       icon: "plus",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "61279014",
  //       submenu: [],
  //     },
  //     {
  //             path: "/tresorerie/main-tresorerie/caisse-actes-externes",
  //             title: "Caisse bureau des entrées",
  //             moduleName: "main-tresorerie",
  //             iconType: "list",
  //             icon: "plus",
  //             class: "ml-menu",
  //             groupTitle: false,
  //             badge: "",
  //             badgeClass: "",
  //             code: "61279014",
  //             submenu: [],
  //           },


  //           {
  //             path: "/tresorerie/main-tresorerie/historique-recettes",
  //             title: "Historique recette",
  //             moduleName: "main-tresorerie",
  //             iconType: "list",
  //             icon: "plus",
  //             class: "ml-menu",
  //             groupTitle: false,
  //             badge: "",
  //             badgeClass: "",
  //             code: "61279014",
  //             submenu: [],
  //           }
  //   ],
  // },

  // {
  //   path: "",
  //   title: "Unité de consultation",
  //   moduleName: "unite-consultation",
  //   iconType: "stethoscope",
  //   icon: "plus",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   code: "57554290",
  //   submenu: [


  //     {
  //       path: "/unite-consultation/archive",
  //       title: "Archives",
  //       moduleName: "unite-consultation",
  //       iconType: "list",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "18282250",
  //       submenu: [],
  //     },
  //     {
  //       path: "/unite-consultation/salle-tri",
  //       title: "Salle de tri",
  //       moduleName: "unite-consultation",
  //       iconType: "list",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "18282250",
  //       submenu: [],
  //     },
  //     {
  //       path: "/unite-consultation/praticien",
  //       title: "Praticiens",
  //       moduleName: "unite-consultation",
  //       iconType: "money",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "58723552",
  //       submenu: [],
  //     },
  //     {
  //       path: "/unite-consultation/historique-consultation",
  //       title: "Historique consultation",
  //       moduleName: "unite-consultation",
  //       iconType: "ambulance",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "45459828",
  //       submenu: [],
  //     },
  //     {
  //       path: "/unite-consultation/dialyse",
  //       title: "Dialyse",
  //       moduleName: "dialyse",
  //       iconType: "list",
  //       icon: "",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       class: "sub-menu-toggle",
  //       code: "57062736",
  //       submenu: [
  //         {
  //           path: "/unite-consultation/dialyse/salle-tri-dialyse",
  //           title: "Prise de constante",
  //           moduleName: "dialyse",
  //           iconType: "",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "86327544",
  //           submenu: [],
  //         },
  //         {
  //           path: "/unite-consultation/dialyse/prescription-hebdo",
  //           title: "Prescritpion hebdo",
  //           moduleName: "dialyse",
  //           iconType: "",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "71818545",
  //           submenu: [],
  //         },
  //         {
  //           path: "/unite-consultation/dialyse/branchement",
  //           title: "Branchement",
  //           moduleName: "unite-consultation",
  //           iconType: "",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "73166694",
  //           submenu: [],
  //         },
  //         {
  //           path: "/unite-consultation/dialyse/seance-dialyse",
  //           title: "Séance dialyse",
  //           moduleName: "unite-consultation",
  //           iconType: "",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "71818545",
  //           submenu: [],
  //         },
  //         {
  //           path: "/unite-consultation/dialyse/debranchement",
  //           title: "Débranchement",
  //           moduleName: "unite-consultation",
  //           iconType: "",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "73166694",
  //           submenu: [],
  //         },
  //         {
  //           path: "/unite-consultation/dialyse/cloture",
  //           title: "Clôture",
  //           moduleName: "unite-consultation",
  //           iconType: "",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "73166694",
  //           submenu: [],
  //         },
  //       ],
  //     },
  //     {
  //       path: "/unite-consultation/soin-ambulatoire",
  //       title: "Soin ambulatoire",
  //       moduleName: "unite-consultation",
  //       iconType: "money",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "48575030",
  //       submenu: [],
  //     },
  //     {
  //       path: "/unite-consultation/exploration-fonctionnelle",
  //       title: "Exploration fonctionnelle",
  //       moduleName: "unite-consultation",
  //       iconType: "money",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "52032688",
  //       submenu: [],
  //     },
  //     {
  //       path: "/unite-consultation/evacuations",
  //       title: "Evacuations",
  //       moduleName: "unite-consultation",
  //       iconType: "ambulance",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "60716507",
  //       submenu: [],
  //     },

  //   ],
  // },


  // {
  //   path: "/radiologie/main-radiologie",
  //   title: "Radiologie",
  //   moduleName: "radiologie",
  //   iconType: "x-ray",
  //   icon: "x-ray",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   code: "57807821",
  //   submenu: [],
  // },
  // {
  //   path: "",
  //   title: "Gestion consommation",
  //   moduleName: "gestion-consomation",
  //   icon: "plus",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   iconType: "sitemap",
  //   badge: "",
  //   badgeClass: "",
  //   code: "50048853",
  //   submenu: [
  //     {
  //       path: "/gestion-consomation/livraison-produit",
  //       title: "Livraison produit",
  //       moduleName: "gestion-consomation",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "5316144",
  //       submenu: [],
  //     },
  //     {
  //       path: "/gestion-consomation/inventaire-stock-unit-fonct",
  //       title: "Inventaire stock",
  //       moduleName: "gestion-consomation",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "19133366",
  //       submenu: [],
  //     },
  //     {
  //       path: "/gestion-consomation/consomation-unit-fonct",
  //       title: "Consommation",
  //       moduleName: "gestion-consomation",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "78424270",
  //       submenu: [],
  //     },
  //     {
  //       path: "/gestion-consomation/produits-units-fonct",
  //       title: "Produit",
  //       moduleName: "gestion-consomation",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "42206479",
  //       submenu: [],
  //     },
  //     {
  //       path: "/gestion-consomation/sortie-diverse-unit-fonct",
  //       title: "Sortie diverse",
  //       moduleName: "gestion-consomation",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "72796397",
  //       submenu: [],
  //     },
  //     {
  //       path: "/gestion-consomation/stock-unit-fonc",
  //       title: "Stock",
  //       moduleName: "gestion-consomation",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "73975537",
  //       submenu: [],
  //     },
  //   ],
  // },

  // {
  //   path: "",
  //   title: "Gestion de la buanderie",
  //   moduleName: "gestion-buanderie",
  //   icon: "plus",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   iconType: "sitemap",
  //   badge: "",
  //   badgeClass: "",
  //   code: "50048853",
  //   submenu: [
  //     {
  //       path: "/gestion-buanderie/lingerie-hors-usage",
  //       title: "Lingerie hors d'usage",
  //       moduleName: "gestion-buanderie",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "5316144",
  //       submenu: [],
  //     },
  //     {
  //       path: "/gestion-buanderie/commande",
  //       title: "Commande",
  //       moduleName: "gestion-buanderie",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "19133366",
  //       submenu: [],
  //     },
  //     {
  //       path: "/gestion-buanderie/traitement-lingerie",
  //       title: "Traitement lingerie",
  //       moduleName: "gestion-buanderie",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "78424270",
  //       submenu: [],
  //     }
  //   ],
  // },

  // {
  //   path: "/laboratoire/main-laboratoire",
  //   title: "Laboratoire",
  //   moduleName: "laboratoire",
  //   iconType: "procedures",
  //   icon: "procedures",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   code: "69906065",
  //   submenu: [],
  // },



  // {
  //   path: "",
  //   title: "Gestion Commerciale",
  //   moduleName: "gestion-commerciale",
  //   iconType: "sitemap",
  //   icon: "monetization_on",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   code: "7653497",
  //   submenu: [
  //     {
  //       path: "/gestion-commerciale/decompte-hospitalisation",
  //       title: "Decompte Hospitalisation",
  //       moduleName: "gestion-commerciale",
  //       iconType: "list",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "7653497",
  //       submenu: [],
  //     },
  //     {
  //       path: "/gestion-commerciale/facturation",
  //       title: "Facturation",
  //       moduleName: "facturation",
  //       iconType: "money-bill-alt",
  //       icon: "",
  //       code: "75447518",
  //       class: "sub-menu-toggle",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       submenu: [
  //         {
  //           path: "/gestion-commerciale/facturation/facture-acte-externe",
  //           title: "Facture acte externe",
  //           moduleName: "facture-acte-externe",
  //           iconType: "wallet",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "7653497",
  //           submenu: [],
  //         },
  //         {
  //           path: "/gestion-commerciale/facturation/facture-hospi",
  //           title: "Facture hospi",
  //           moduleName: "facture-hospi",
  //           iconType: "wallet",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "7653497",
  //           submenu: [],
  //         },
  //         {
  //           path: "/gestion-commerciale/facturation/facture-dialyse",
  //           title: " Facture dialyse",
  //           moduleName: "facture-dialyse",
  //           iconType: "money-bill-alt",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "7653497",
  //           submenu: [],
  //         },
  //         {
  //           path: "/gestion-commerciale/facturation/facture-pharmacie",
  //           title: "Facture pharmacie",
  //           moduleName: "facture-pharmacie",
  //           iconType: "receipt",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "7653497",
  //           submenu: [],
  //         },
  //       ],
  //     },
  //     {
  //       path: "/gestion-commerciale/echeance",
  //       title: "Echeance",
  //       moduleName: "echeance",
  //       iconType: "money-bill-alt",
  //       icon: "",
  //       code: "75447518",
  //       class: "sub-menu-toggle",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       submenu: [
  //         {
  //           path: "/gestion-commerciale/echeance/echeance-acte-externe",
  //           title: "Echeance acte externe",
  //           moduleName: "echeance-acte-externe",
  //           iconType: "wallet",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "7653497",
  //           submenu: [],
  //         },
  //         {
  //           path: "/gestion-commerciale/echeance/echeance-decompte-hospi",
  //           title: "Echeance hospi",
  //           moduleName: "echeance-decompte-hospi",
  //           iconType: "wallet",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "7653497",
  //           submenu: [],
  //         },
  //         {
  //           path: "/gestion-commerciale/echeance/echeance-facture-dialise",
  //           title: " Echeance dialyse",
  //           moduleName: "echeance-facture-dialise",
  //           iconType: "money-bill-alt",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "7653497",
  //           submenu: [],
  //         },
  //         {
  //           path: "/gestion-commerciale/echeance/echeance-vente-pharmacie-vd",
  //           title: "Echeance pharmacie VD",
  //           moduleName: "echeance-vente-pharmacie-vd",
  //           iconType: "receipt",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "7653497",
  //           submenu: [],
  //         },

  //         {
  //           path: "/gestion-commerciale/echeance/echeance-vente-pharmacie-aexterne",
  //           title: "Echeance pharmacie V AE",
  //           moduleName: "echeance-vente-pharmacie-aexterne",
  //           iconType: "wallet",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "7653497",
  //           submenu: [],
  //         },
  //       ],
  //     },
  //     {
  //       path: "/gestion-commerciale/bordereau",
  //       title: "Bordereau",
  //       moduleName: "bordereau",
  //       iconType: "money-bill-alt",
  //       icon: "",
  //       code: "75447518",
  //       class: "sub-menu-toggle",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       submenu: [
  //         {
  //           path: "/gestion-commerciale/bordereau/bordereau-acte-externe",
  //           title: "Bordereau acte externe",
  //           moduleName: "bordereau-acte-externe",
  //           iconType: "wallet",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "7653497",
  //           submenu: [],
  //         },
  //         {
  //           path: "/gestion-commerciale/bordereau/bordereau-hospi",
  //           title: "Bordereau hospi",
  //           moduleName: "bordereau-hospi",
  //           iconType: "wallet",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "7653497",
  //           submenu: [],
  //         },
  //         {
  //           path: "/gestion-commerciale/bordereau/bordereau-pharmacie",
  //           title: "Bordereau pharmacie",
  //           moduleName: "bordereau-pharmacie",
  //           iconType: "money-bill-alt",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "7653497",
  //           submenu: [],
  //         },
  //       ],
  //     },
  //   ],
  // },
  // // Common Modules


  // {
  //   path: "",
  //   title: "Pharmacie",
  //   moduleName: "pharmacie",
  //   iconType: "hospital",
  //   icon: "description",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   code: "91046131",
  //   submenu: [
  //     {
  //       path: "/pharmacie/commande-medicament-pharmacie",
  //       title: "Commande médicament",
  //       moduleName: "pharmacie",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "69716826",
  //       submenu: [],
  //     },
  //     {
  //       path: "/pharmacie/livraison-medicament-pharmacie",
  //       title: "Livraison médicament",
  //       moduleName: "pharmacie",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "94100990",
  //       submenu: [],
  //     },
  //     {
  //       path: "/pharmacie/gestion-de-stock",
  //       title: "Gestion de stock",
  //       moduleName: "gestion-de-stock",
  //       iconType: "",
  //       icon: "",
  //       // class: "ml-menu",
  //       code: "67938424",
  //       class: "sub-menu-toggle",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       submenu: [
  //         {
  //           path: "/pharmacie/gestion-de-stock/catalogue-fournisseur",
  //           title: "Catalogue fournisseur",
  //           moduleName: "catalogue-fournisseur",
  //           iconType: "",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "69716826",
  //           submenu: [],
  //         },
  //         {
  //           path: "/pharmacie/gestion-de-stock/rangement-medicament",
  //           title: "Range medicament",
  //           moduleName: "rangement-medicament",
  //           iconType: "",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "69716826",
  //           submenu: [],
  //         },
  //         {
  //           path: "/pharmacie/gestion-de-stock/sortiee-diverse",
  //           title: "Sortie diverse",
  //           moduleName: "sortiee-diverse",
  //           iconType: "",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "69716826",
  //           submenu: [],
  //         },
  //         {
  //           path: "/pharmacie/gestion-de-stock/transfert-medicament",
  //           title: "Transfert medicament",
  //           moduleName: "transfert-medicament",
  //           iconType: "",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "69716826",
  //           submenu: [],
  //         },
  //       ],
  //     },
  //     {
  //       path: "/pharmacie/inventaire-de-stock",
  //       title: "Inventaire de stock",
  //       moduleName: "pharmacie",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "49909026",
  //       submenu: [],
  //     },
  //     {
  //       path: "/pharmacie/vente-medicaments",
  //       title: "Vente de médicament",
  //       moduleName: "pharmacie",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "7674225",
  //       submenu: [],
  //     },
  //     {
  //       path: "/pharmacie/retour-medicaments",
  //       title: "Retour medicaments",
  //       moduleName: "pharmacie",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "23672516",
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: "",
  //   title: "Unité de soins",
  //   moduleName: "hospitalisation",
  //   iconType: "hospital-alt",
  //   icon: "description",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   code: "54186537",
  //   submenu: [
  //     {
  //       path: "/hospitalisation/demande-hospi",
  //       title: "Création dossier",
  //       moduleName: "demande hospi",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "54078828",
  //       submenu: [],
  //     },
  //     {
  //       path: "/hospitalisation/dossier-hospi",
  //       title: "Dossier hospi",
  //       moduleName: "dossier hospi",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "99605162",
  //       submenu: [],
  //     },


  //     {
  //       path: "/hospitalisation/attribution-lit",
  //       title: "Attribution lit",
  //       moduleName: "attribution-lit",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "38744841",
  //       submenu: [],
  //     },

  //     {
  //       path: "/hospitalisation/preparation-lit",
  //       title: "Préparation-lit",
  //       moduleName: "preparation-lit",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "75821978",
  //       submenu: [],
  //     },
  //     {
  //       path: "/hospitalisation/commande-medicament",
  //       title: "Commande medicament",
  //       moduleName: "commande-medicament",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "15559692",
  //       submenu: [],
  //     },
  //     {
  //       path: "/hospitalisation/fiche-engagement",
  //       title: "Fiche engagement",
  //       moduleName: "fiche-engagement",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "16693399",
  //       submenu: [],
  //     },
  //     {
  //       path: "/hospitalisation/execution-soins",
  //       title: "Execution soins",
  //       moduleName: "execution-soins",
  //       iconType: "",
  //       icon: "",
  //       // class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "75447518",
  //       class: "sub-menu-toggle",
  //       submenu: [
  //         {
  //           path: "/hospitalisation/execution-soins/soins-infirmier",
  //           title: "Soins infirmier",
  //           moduleName: "execution-soins",
  //           iconType: "",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "7653497",
  //           submenu: [],
  //         },
  //         {
  //           path: "/hospitalisation/execution-soins/transfusion-sanguine",
  //           title: "Transfusion sanguine",
  //           moduleName: "execution-soins",
  //           iconType: "",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "7653497",
  //           submenu: [],
  //         },
  //         {
  //           path: "/hospitalisation/execution-soins/toilette-malade",
  //           title: "Toilette malade",
  //           moduleName: "execution-soins",
  //           iconType: "",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "7653497",
  //           submenu: [],
  //         },
  //         {
  //           path: "/hospitalisation/execution-soins/prise-de-constante",
  //           title: "Prise de constante",
  //           moduleName: "execution-soins",
  //           iconType: "",
  //           icon: "",
  //           class: "ml-menu",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           code: "7653497",
  //           submenu: [],
  //         },
  //       ],
  //     },
  //     {
  //       path: "/hospitalisation/visite-medecin",
  //       title: "Visite medecin",
  //       moduleName: "visite-medecin",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "31280887",
  //       submenu: [],
  //     },
  //     {
  //       path: "/hospitalisation/bon-de-sortie",
  //       title: "Bon de sortie",
  //       moduleName: "hospitalisation",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "13043680",
  //       submenu: [],
  //     },

  //     // {
  //     //   path: "/hospitalisation/dossier-hospi-lit",
  //     //   title: "Dossier hospi lit",
  //     //   moduleName: "dossier hospi lit",
  //     //   iconType: "",
  //     //   icon: "",
  //     //   class: "ml-menu",
  //     //   groupTitle: false,
  //     //   badge: "",
  //     //   badgeClass: "",
  //     //   code:'7653497',
  //     //   submenu: [],
  //     // },
  //   ],
  // },

  // {
  //   path: "",
  //   title: "Corbeilles",
  //   moduleName: "corbeilles",
  //   iconType: "x-ray",
  //   icon: "x-ray",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   code: "92977000",
  //   submenu: [
  //     {
  //       path: "/corbeilles/bureau-entrees",
  //       title: "Bureau des entrées",
  //       moduleName: "parametres",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       code: "54765596",
  //       submenu: [],
  //     },

  // //     {
  // //       path: "/parametres/prevention",
  // //       title: "Prévention",
  // //       moduleName: "parametres",
  // //       iconType: "",
  // //       icon: "",
  // //       class: "ml-menu",
  // //       groupTitle: false,
  // //       badge: "",
  // //       badgeClass: "",
  // //       code: "76383340",
  // //       submenu: [],
  // //     },
  // //     {
  // //       path: "/parametres/service-technique",
  // //       title: "Service Technique",
  // //       moduleName: "parametres",
  // //       iconType: "",
  // //       icon: "",
  // //       class: "ml-menu",
  // //       groupTitle: false,
  // //       badge: "",
  // //       badgeClass: "",
  // //       code: "68756442",
  // //       submenu: [],
  // //     },
  //   ],
  // },

  //////////////////////////////////////////////////////////
  {
    path: "",
    title: "Action de Masse",
    moduleName: "action-max",
    iconType: "cog",
    icon: "description",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    code: "FUNC-VFEI",
    submenu: [
      {
        path: "/action-max/blocage-masse",
        title: "Blocage",
        moduleName: "blocage-masse",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        code: "FUNC-YNVJ",
        submenu: [],
      },
      {
        path: "/action-max/deblocage-masse",
        title: "Deblocage",
        moduleName: "deblocage-masse",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        code: "FUNC-UZXF",
        submenu: []
      },
      {
        path: "/action-max/mise-en-machine-de-masse",
        title: "Mise en Machine",
        moduleName: "mise-en-machine-de-masse",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        code: "FUNC-YZAN",
        submenu: [],
      },
      {
        path: "/action-max/blocage-automatique",
        title: "Blocage automatique",
        moduleName: "blocage-automatique",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        code: "FUNC-JWQW",
        submenu: []
      }
    ],
  },


  ///////////////////////////////////////////////////////////
  {
    path: "",
    title: "Paramètres",
    moduleName: "parametres",
    iconType: "cog",
    icon: "description",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    code: "FUNC-YIR3",
    submenu: [
      {
        path: "/parametres/utilisateurs",
        title: "Utilisateurs",
        moduleName: "utilisateurs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        code: "FUNC-8EQO",
        submenu: [],
      },
      {
        path: "/parametres/roles",
        title: "Profil",
        moduleName: "roles",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        code: "FUNC-ZLRP",
        submenu: [],
      },
      {
        path: "/parametres/fonctionnalites",
        title: "Fonctionnalites",
        moduleName: "fonctionnalites",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        code: "FUNC-FNXQ",
        submenu: [],
      },
      {
        path: "/parametres/liste-diffusions",
        title: "Liste de diffusions",
        moduleName: "diffusion-list",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        code: "FUNC-RLES",
        submenu: [],
      },
      {
        path: "/parametres/sms-exclusions",
        title: "SMS Inclusions",
        moduleName: "fonctionnalites",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        code: "FUNC-X2EE",
        submenu: [],
      },
      // {
      //   path: "/parametres/log-connexion",
      //   title: "Connexion",
      //   moduleName: "log-connection",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   code: "FUNC-X2EE",
      //   submenu: [],
      // }
    ],
  },
  {
    path: "",
    title: "Logs",
    moduleName: "logs",
    iconType: "history",
    icon: "description",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    //code: "FUNC-TRKW",
    code: "FUNC-5VEH",
    submenu: [
      {
        path: "/logs/main-historique",
        title: "Historique",
        moduleName: "main-historique",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        code: "FUNC-EOHX",
        submenu: [],
      },
      {
        path: "/logs/log-action-numero",
        title: "Action Numéro",
        moduleName: "log-action-numero",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        code: "FUNC-SHJV",
        submenu: [],
      },
      {
        path: "/logs/log-action",
        title: "Action",
        moduleName: "log-action",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        code: "FUNC-AHAF",
        submenu: []
      },
      {
        path: "/logs/log-mes-actions",
        title: "Mes Logs",
        moduleName: "log-action-perso",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        code: "FUNC-CSTS",
        submenu: []
      },
      {
        path: "/logs/log-alertes",
        title: "Log Alertes",
        moduleName: "log-alert",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        code: "FUNC-CUFB",
        submenu: []

      },
       {
        path: "/logs/log-connexion",
         title: "Connexion",
         moduleName: "log-connection",
         iconType: "",
         icon: "",
         class: "ml-menu",
         groupTitle: false,
         badge: "",
         badgeClass: "",
         code: "FUNC-ABSS",
         //code: "FUNC-E4RE",
         submenu: [],
       },
    ],
  },
];
