/*
 * Created on 2023-06-28 ( Time 20:24:52 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package ci.smile.simswaporange.dao.entity;

import java.io.Serializable;

import lombok.*;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "action_en_masse"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@ToString
@Entity
@Table(name="action_en_masse" )
public class ActionEnMasse implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="code", length=255)
    private String     code         ;

    @Column(name="libelle", length=255)
    private String     libelle      ;

    @Column(name="lien_fichier", length=255)
    private String     lienFichier  ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at")
    private Date       createdAt    ;

    @Column(name="is_deleted")
    private Boolean    isDeleted    ;

    @Column(name="updated_by")
    private Integer    updatedBy    ;

    @Column(name="created_by")
    private Integer    createdBy    ;

    @Column(name="identifiant", length=100)
    private String     identifiant  ;

    @Column(name="is_ok")
    private Boolean    isOk         ;

    @Column(name="lien_import", length=2147483647)
    private String     lienImport   ;

    @Column(name="link_download", length=2147483647)
    private String     linkDownload ;

    @Column(name="put_on")
    private Boolean    putOn        ;

    @Column(name="put_of")
    private Boolean    putOf        ;

    @Column(name="link_download_masse", length=2147483647)
    private String     linkDownloadMasse ;

    @Column(name="error")
    private Boolean    error        ;

    @Column(name="is_automatically")
    private Boolean    isAutomatically ;

    @Column(name="is_deblocage_en_masse")
    private Boolean    isDebloageEnMasse ;


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ActionEnMasse() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
