/*
 * Created on 2024-01-11 ( Time 09:57:48 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package ci.smile.simswaporange.dao.entity;

import java.io.Serializable;

import lombok.*;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "action_utilisateur"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@ToString
@Entity
@Table(name="action_utilisateur" )
public class ActionUtilisateur implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Temporal(TemporalType.DATE)
    @Column(name="date")
    private Date       date         ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at")
    private Date       createdAt    ;

    @Column(name="created_by")
    private Integer    createdBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

    @Column(name="updated_by")
    private Integer    updatedBy    ;

    @Column(name="is_deleted")
    private Boolean    isDeleted    ;

    @Column(name="numero", length=2147483647)
    private String     numero       ;

    @Column(name="motif", length=2147483647)
    private String     motif        ;

    @Column(name="empreinte", length=2147483647)
    private String     empreinte    ;

    @Column(name="is_excel_number")
    private Boolean    isExcelNumber ;

    @Column(name="statut", length=100)
    private String     statut       ;

    @Column(name="is_machine")
    private Boolean    isMachine    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_machine_date")
    private Date       lastMachineDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_debloquage")
    private Date       lastDebloquage ;

    @Column(name="status_bscs", length=100)
    private String     statusBscs   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="activation_date")
    private Date       activationDate ;

    @Column(name="offer_name", length=100)
    private String     offerName    ;

    @Column(name="from_bss")
    private Boolean    fromBss      ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_blocage_date")
    private Date       lastBlocageDate ;

    @Column(name="contract_id", length=100)
    private String     contractId   ;

    @Column(name="port_number", length=100)
    private String     portNumber   ;

    @Column(name="serial_number", length=100)
    private String     serialNumber ;

    @Column(name="tm_code", length=100)
    private String     tmCode       ;

	// "idStatus" (column "id_status") is not defined by itself because used as FK in a link 
	// "idUser" (column "id_user") is not defined by itself because used as FK in a link 
	// "idProfil" (column "id_profil") is not defined by itself because used as FK in a link 
	// "idCategory" (column "id_category") is not defined by itself because used as FK in a link 
	// "typeNumeroId" (column "type_numero_id") is not defined by itself because used as FK in a link 

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="type_numero_id", referencedColumnName="id")
    private TypeNumero typeNumero  ;
    @ManyToOne
    @JoinColumn(name="id_status", referencedColumnName="id")
    private Status status      ;
    @ManyToOne
    @JoinColumn(name="id_category", referencedColumnName="id")
    private Category category    ;
    @ManyToOne
    @JoinColumn(name="id_user", referencedColumnName="id")
    private User user        ;
    @ManyToOne
    @JoinColumn(name="id_profil", referencedColumnName="id")
    private Profil profil      ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ActionUtilisateur() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
