/*
 * Created on 2023-06-29 ( Time 14:15:45 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package ci.smile.simswaporange.dao.entity;

import java.io.Serializable;

import lombok.*;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "ation_to_notifiable"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@ToString
@Entity
@Table(name="ation_to_notifiable" )
public class AtionToNotifiable implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="numero", length=255)
    private String     numero       ;

    @Column(name="is_notify")
    private Boolean    isNotify     ;

    @Column(name="is_en_masse")
    private Boolean    isEnMasse    ;

    @Column(name="statut_action", length=2147483647)
    private String     statutAction ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at")
    private Date       createdAt    ;

    @Column(name="created_by")
    private Integer    createdBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

    @Column(name="updated_by")
    private Integer    updatedBy    ;

    @Column(name="is_deleted")
    private Boolean    isDeleted    ;

    @Column(name="message", length=2147483647)
    private String     message      ;

	// "idStatus" (column "id_status") is not defined by itself because used as FK in a link 
	// "idUserDemand" (column "id_user_demand") is not defined by itself because used as FK in a link 
	// "idUserValid" (column "id_user_valid") is not defined by itself because used as FK in a link 
	// "idAction" (column "id_action") is not defined by itself because used as FK in a link 

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="id_user_demand", referencedColumnName="id")
    private User user        ;
    @ManyToOne
    @JoinColumn(name="id_action", referencedColumnName="id")
    private ActionSimswap actionSimswap;
    @ManyToOne
    @JoinColumn(name="id_status", referencedColumnName="id")
    private Status status      ;
    @ManyToOne
    @JoinColumn(name="id_user_valid", referencedColumnName="id")
    private User user2       ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public AtionToNotifiable() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
