/*
 * Created on 2023-08-08 ( Time 13:26:59 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package ci.smile.simswaporange.dao.entity;

import java.io.Serializable;

import lombok.*;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "demande"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@ToString
@Entity
@Table(name="demande" )
public class Demande implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="numero", length=2147483647)
    private String     numero       ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at")
    private Date       createdAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

    @Column(name="is_deleted")
    private Boolean    isDeleted    ;

    @Column(name="is_transfert")
    private Boolean    isTransfert    ;

    @Column(name="created_by")
    private Integer    createdBy    ;

    @Column(name="updated_by_telco")
    private Integer    updatedByTelco ;

    @Column(name="motif", length=2147483647)
    private String     motif        ;

    @Column(name="offer_name", length=100)
    private String     offerName    ;
    
    @Column(name="updated_by")
    private Integer    updatedBy;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="activation_date")
    private Date       activationDate ;

    @Column(name="status_bscs", length=100)
    private String     statusBscs   ;

    @Column(name="is_validated")
    private Boolean    isValidated  ;
    
    @Column(name="two_bool")
    private Boolean    twoBool;

    @Column(name="updated_by_omci")
    private Integer    updatedByOmci ;
    
    @Column(name="serial_number", length=100)
    private String     serialNumber    ;
    
    @Column(name="port_number", length=100)
    private String     portNumber    ;
    
    @Column(name="contract_id", length=100)
    private String     contractId    ;
   

	// "idUser" (column "id_user") is not defined by itself because used as FK in a link 
	// "idTypeDemande" (column "id_type_demande") is not defined by itself because used as FK in a link 
	// "idStatus" (column "id_status") is not defined by itself because used as FK in a link 
	// "typeNumeroId" (column "type_numero_id") is not defined by itself because used as FK in a link 
	// "idTypeCategory" (column "id_type_category") is not defined by itself because used as FK in a link 

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="id_type_category", referencedColumnName="id")
    private Category category    ;
    @ManyToOne
    @JoinColumn(name="id_status", referencedColumnName="id")
    private Status status      ;
    @ManyToOne
    @JoinColumn(name="id_user", referencedColumnName="id")
    private User user        ;
    @ManyToOne
    @JoinColumn(name="type_numero_id", referencedColumnName="id")
    private TypeNumero typeNumero  ;
    @ManyToOne
    @JoinColumn(name="id_type_demande", referencedColumnName="id")
    private TypeDemande typeDemande ;
    @ManyToOne
    @JoinColumn(name = "id_action_en_masse", referencedColumnName = "id")
    private ActionEnMasse actionEnMasse;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Demande() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
