/*
 * Created on 2023-07-04 ( Time 13:18:47 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package ci.smile.simswaporange.dao.entity;

import java.io.Serializable;

import lombok.*;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "tache"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@ToString
@Entity
@Table(name="tache" )
public class Tache implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at")
    private Date       createdAt    ;

    @Column(name="is_deleted")
    private Boolean    isDeleted    ;

    @Column(name="updated_by")
    private Integer    updatedBy    ;

    @Column(name="created_by")
    private Integer    createdBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_demande")
    private Date       dateDemande  ;

	// "idUser" (column "id_user") is not defined by itself because used as FK in a link 
	// "idTypeDemande" (column "id_type_demande") is not defined by itself because used as FK in a link 
	// "idDemande" (column "id_demande") is not defined by itself because used as FK in a link 
	// "idActionEnMasse" (column "id_action_en_masse") is not defined by itself because used as FK in a link 
	// "idStatus" (column "id_status") is not defined by itself because used as FK in a link 
	// "idActionSimswap" (column "id_action_simswap") is not defined by itself because used as FK in a link 

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="id_action_en_masse", referencedColumnName="id")
    private ActionEnMasse actionEnMasse;
    @ManyToOne
    @JoinColumn(name="id_action_simswap", referencedColumnName="id")
    private ActionSimswap actionSimswap;
    @ManyToOne
    @JoinColumn(name="id_demande", referencedColumnName="id")
    private Demande demande     ;
    @ManyToOne
    @JoinColumn(name="id_status", referencedColumnName="id")
    private Status status      ;
    @ManyToOne
    @JoinColumn(name="id_type_demande", referencedColumnName="id")
    private TypeDemande typeDemande ;
    @ManyToOne
    @JoinColumn(name="id_user", referencedColumnName="id")
    private User user        ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Tache() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
